version: 2.1

jobs:
  hello-world:
    docker:
      - image: circleci/node:15.14.0
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo "Hello world!"

workflows:
  build:
    jobs:
      - hello-world:
          name: hw1
      - hello-world:
          name: hw2
          filters:
            branches:
              only:
                - master
